apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      cliFlags:
      - --load
      dockerfile: Dockerfile
      noCache: true
  tagPolicy:
    gitCommit: {}
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0