apiVersion: skaffold/v4beta8
kind: Config
build:
  artifacts:
  - image: ghcr.io/seventieskid/busybox
    context: .
    docker:
      cliFlags:
      - --load      # Ensures image is available in docker image store
      dockerfile: Inner-Dockerfile
      noCache: true
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0